version: 2.1
orbs:
  aws-ecr-eks: signavio/aws-ecr-eks@2.4.0
workflows:
  version: 2
  aws-ecr-eks:
    jobs:
      - build-push-restart:
          context: aws
          repo: site
          deployment_name: web
          k8s_namespace: default
