version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.1.0
workflows:
  build_and_push_image:
    jobs:
      - aws-eks/update-container-image:
          context: aws
          aws-region: $AWS_REGION
          cluster-name: hasan-southeast
          resource-name: deployment/web
          namespace: default
          container-image-updates: '265747058112.dkr.ecr.ap-southeast-1.amazonaws.com/site=265747058112.dkr.ecr.ap-southeast-1.amazonaws.com/site:latest'
